### ISSUE TITLE
Failure when impersonating a service in an Akka cluster

### ISSUE THREAD

**Issue by eyalb181** [metalbear-co/mirrord#1041]
### Bug Description

When impersonating a pod in an Akka cluster, the local process makes the initial gossip request in order to join the cluster. This communication fails, so the service doesn't join the cluster and everything else fails as well.

### Steps to Reproduce

Impersonate a pod in an Akka cluster

### Relevant Logs

```shell
"Cluster Node [akka.tcp://ClusterSystem@10.0.0.26:2551] - Couldn't join seed nodes after [6] attempts, will try again. seed-nodes=[akka.tcp://ClusterSystem@akka-cluster1:2551, akka.tcp://ClusterSystem@akka-cluster2:2551, akka.tcp://ClusterSystem@akka-cluster3:2551, akka.tcp://ClusterSystem@akka-cluster4:2551]"


Association with remote system [akka.tcp://ClusterSystem@10.99.126.148:2551] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://ClusterSystem@10.99.126.148:2551]] Caused by: [java.net.SocketException: Unknown error: 111]"
```

### Your operating system and version

MacOS

### Local process

Scala

**Comment by aviramha** [comment]
This happens via JetBrains so might be that we just don't load since we don't support sbt?

p.s setting up Akka in k8s
https://github.com/akka/akka-sample-cluster-kubernetes-scala

**Comment by aviramha** [comment]
Managed to reproduce it. Setup cluster:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appka
  name: appka
  namespace: appka-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: appka
  template:
    metadata:
      labels:
        app: appka
        actorSystemName: appka
    spec:
      containers:
      - name: appka
        image: docker.io/aviramhassan/akka-sample-cluster-kubernetes:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ready
            port: management
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: "/alive"
            port: management
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 20
        ports:
        # akka-management and bootstrap
        - name: management
          containerPort: 8558
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REQUIRED_CONTACT_POINT_NR
          value: "3"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: appka-1
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: appka-1
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
- kind: User
  name: system:serviceaccount:appka-1:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

```
