### ISSUE TITLE
Liveness probes failing when stealing from an express app

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1402]
### Bug Description

It seems that neither the deployed app nor the local one answer the probes successfully, so the pod is getting restarted repeatedly.
So far not reproduced by the team.

### Steps to Reproduce

Unsuccessful steps so far:

Created express app with nx:
```bash
git clone https://github.com/nrwl/nx-examples
cd nx-examples
npm install -g pnpm
pnpm install
pnpm install --save-dev @nrwl/node
pnpm nx g @nrwl/node:app express-app --framework express
```

Dockerfile
```Dockerfile
FROM node:lts-alpine
WORKDIR /app
COPY ./dist/apps/express-app .
ENV PORT=80
EXPOSE ${PORT}
RUN npm install --production
RUN npm install reflect-metadata tslib rxjs @nestjs/platform-express
CMD node ./main.js
```

```
docker buildx build -t pnpm-nx-express . --platform linux/amd64 && docker tag pnpm-nx-express t4lz/pnpm-nx-express && docker push t4lz/pnpm-nx-express
```

remote.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: docker.io/t4lz/pnpm-nx-express
          ports:
            - name: http
              containerPort: 80
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "80"
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 12
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 12
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: express
  name: express
spec:
  ports:
    - port: 30002
      protocol: TCP
      targetPort: 80
  selector:
    app: express
  sessionAffinity: None
  type: LoadBalancer

```

```
kubectl apply -f remote.yaml
```

```
PORT=80 HOST=0.0.0.0 mirrord exec --fs-mode=local -a default --target deploy/express --agent-ttl=30 --steal pnpm nx serve express-app1
```

Also added logs to request handling and saw all the probes coming on time.

### Your operating system and version

macOS

### Local process

env/node (pnpm is a `!#/usr/bin/env node` script)

### Additional Info

nginx-ingress
