### ISSUE TITLE
kube oidc refresh doesn't happen

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1460]
probably upstream issue in kube-rs, but need to investigate and create issue when we understand it's there:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ca-data
    server: https://127.0.0.1:6443
  name: cluster-name
contexts:
- context:
    cluster: cluster-name
    user: user-cluster-name
  name: cluster-name
current-context: cluster-name
kind: Config
preferences: {}
users:
- name: user-cluster-name
  user:
    auth-provider:
      config:
        client-id: cluster-name
        client-secret: secret
        id-token: id-token
        idp-issuer-url: https://dex.server.tld
        refresh-token: refresh-token
      name: oidc
```
mirrord doesn't refresh the token.
