### ISSUE TITLE
Many Rust panics when running sh from vscode

### ISSUE THREAD

**Issue by t4lz** [metalbear-co/mirrord#1792]
### Bug Description

While using mirrord from vscode to run a node service with a `node-terminal` launch configurations, some users are seeing a lot of those panic logs while their service starts. Mirrord and the service seems to work despite the panics. So this issue does not (yet) prevent them from successfully using mirrord, but it looks bad and it's confusion. 

### Steps to Reproduce

`mirrord.json`
```json
{
    "target": {
        "path": "pod/my-pod-3141592",
        "namespace": "my-namespace"
    },
    "feature": {
        "fs": {
            "mode": "read",
            "read_only": [
                "/etc/config/config.+"
            ]
        },
        "network": {
            "incoming": "steal",
            "outgoing": true
        }
    }
}
```

`launch.yaml`
```yaml
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node-terminal",
            "name": "see panics",
            "request": "launch",
            "nodeVersionHint": 18,
            "command": "source ~/.nvm/nvm.sh; nvm use; yarn start:service",
            "env": {
                "RUST_LOG": "mirrord=trace",
                "RUST_BACKTRACE": "1"
            }
        }
    ]
}
```

### Backtrace

```shell
thread '<unnamed>' panicked at 'failed to wake I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/io/mod.rs:255:27
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: tokio::runtime::time::<impl tokio::runtime::time::handle::Handle>::reregister
   4: tokio::runtime::time::entry::TimerEntry::poll_elapsed
   5: <tokio::time::sleep::Sleep as core::future::future::Future>::poll
   6: tokio::time::interval::Interval::poll_tick
   7: mirrord_layer::thread_loop::{{closure}}
   8: tokio::runtime::scheduler::current_thread::Context::enter
   9: tokio::runtime::context::scoped::Scoped<T>::set
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  11: tokio::runtime::context::runtime::enter_runtime
  12: tokio::runtime::runtime::Runtime::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'failed to wake I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/io/mod.rs:255:27
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: tokio::runtime::time::<impl tokio::runtime::time::handle::Handle>::reregister
   4: tokio::runtime::time::entry::TimerEntry::poll_elapsed
   5: <tokio::time::sleep::Sleep as core::future::future::Future>::poll
   6: tokio::time::interval::Interval::poll_tick
   7: mirrord_layer::thread_loop::{{closure}}
   8: tokio::runtime::scheduler::current_thread::Context::enter
   9: tokio::runtime::context::scoped::Scoped<T>::set
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  11: tokio::runtime::context::runtime::enter_runtime
  12: tokio::runtime::runtime::Runtime::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Your operating system and version

macOS

### Local process

sh

### Additional Info

will update the issue if I get some logs from around the panics.
