### ISSUE TITLE
Rollout: env values are not picked up

### ISSUE THREAD

**Issue by patdlanger** [metalbear-co/mirrord#2085]
### Bug Description

Given an ArgoCd Rollout with below config 
```
spec:
      containers:
        - env:
          - name: GROUP_INSTANCE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ABC
            value: 'someValue'
          - name: JAVA_TOOL_OPTIONS
            value: '-Xms{{.Values.jvm.heap}} -Xmx{{.Values.jvm.heap}} -XX:HeapDumpPath=/dumps'
          envFrom:
          - configMapRef:
              name: {{ template "xyz.fullname" . }}
```

None of the set env values are available in my process, neither `ABC` nor any contained in the configmap

### Steps to Reproduce

Create a rollout with given spec above
run mirrord on it
check the env variables

### Your operating system and version

Ubuntu 22.04.2 LTS, Intellij Idea Ultimate 2023.2,mirrord 3.75.3, mirrord plugin 3.56.0

### Local process

a java process within Intellij Idea Ultimate 2023.2

**Comment by aviramha** [comment]
Thanks for reporting this. Can you share your mirrord.json file? Specifically, do you use the ephemeral feature?

**Comment by patdlanger** [comment]
```yaml
---
target:
    path:
        rollout: service-name
    namespace: namespace
accept_invalid_certificates: false
feature:
    network:
        incoming:
            mode: mirror
            ignore_ports:
                - 8181
        outgoing: true
    fs: read
```
this is my config, but I just realized that even the configmap mapped env values are not picked up, I'll update the description

**Comment by aviramha** [comment]
Any chance you have more than one container in the target?

**Comment by patdlanger** [comment]
In the rollout itself I defined 2 containers

**Comment by aviramha** [comment]
Then it might be mirrord is targetting the other container (not the one you want it to target)
To specify a specific container, change your yaml to be like:
```yaml
---
target:
    path:
        rollout: service-name
        container: desired-container
    namespace: namespace
accept_invalid_certificates: false
feature:
    network:
        incoming:
            mode: mirror
            ignore_ports:
                - 8181
        outgoing: true
    fs: read
```
