### ISSUE TITLE
Unable to mirror/steal traffic from one container to another inside the same pod

### ISSUE THREAD

**Issue by mattiaforc** [metalbear-co/mirrord#2154]
### Bug Description

Hello everyone, I am trying to mirror/steal traffic from a pod that has 2 containers. My production use case is that I have an oauth2-proxy (let's say, port 80) that receives traffic from other services in my cluster, and forwards the valid requests to another container inside the pod which is my actual application (port 8080). I managed to create a very simple reproducible example below, where I use some "mock" containers to emulate the reverse proxy -> application functionality. 
I believe this happens only for traffic between the proxy and the application, because if I call the application directly (for example via an ingress that targets the application port directly) it works fine and I am able to see traffic mirrored to my application in IntelliJ.

I know that istio or other service meshes are not supported, but I wanted to check with you if my case could resemble a service mesh or if this is supposed to work! I tried both mirror and steal mode, with no success. I also tried fiddling with the configuration, for example by setting `ignore_localhost` to `false`, `true`, and combination of `incoming` and `outgoing` but nothing worked.

If I managed to get this working, mirrord would be terrific for our developers - it's the only missing thing for us :)

### Steps to Reproduce

1. Define a pod with two containers, the first could be a simple echo-server, the second is a simple reverse proxy sidecar (this is the most basic reproducible example i could come up with!):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  labels:
    app: my-api
spec:
  selector:
    matchLabels:
      app: my-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: my-api
          image: jmalloc/echo-server
          ports:
            - name: main
              containerPort: 8080
              protocol: TCP
        - name: proxy
          image: 'schmailzl/simple-reverse-proxy'
          env:
            - name: PROXY_URL
              value: "http://localhost:8080"
          ports:
            - name: proxy
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-api
spec:
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-api
  type: ClusterIP
```

2. Create a mirrord.json to use:
```json
{
  "agent": {
    "ephemeral": true,
    "log_level": "mirrord=trace"
  },
  "target": {
    "namespace": "default",
    "path": "deployment/my-api/container/my-api"
  },
  "feature": {
    "network": {
      "incoming": {
        "mode": "mirror",
        "ignore_localhost": false
      },
      "outgoing": {
        "tcp": true,
        "udp": true,
        "ignore_localhost": false
      }
    },
    "fs": "read",
    "env": true
  },
  "operator": false
}
```

3. Simple python webserver (that at least should show the incoming requests): 
```bash
mirrord exec -f .mirrord/mirrord.json -- python3 -m http.server 8080
```

4. Test it via another container:
```bash
kubectl run --rm -it test --image wbitt/network-multitool -- /bin/bash

(inside the container)
bash-5.1# curl http://my-api:80
Request served by my-api-8f59f7cb7-n554q

GET / HTTP/1.0

Host: localhost:8080
Accept: */*
Connection: close
User-Agent: curl/7.80.0
```

5. The mirrord pyhton web server received nothing. I expect the following traffic flow: 
```bash
container proxy (port 80)   -> container my-api (port 8080)
            (mirror/steal)  -> mirrord python3 webserver (port 8080)
```

### Your operating system and version

ubuntu 22.04 kernel 5.19.0-41-generic

### Local process

mirrord 3.72.1
