### ISSUE TITLE
dapr sidecar isn't accessible

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2597]
When running curl in a `mirrord exec` ran as the main app, it cannot access the gRPC port (50001) or the health check (3500).
When using ephemeral agent, the health check works but still can't access the gRPC port.
https://discord.com/channels/933706914808889356/1261388094746267811

mirrord config 
```json
{
  "internal_proxy": {"log_level": "mirrord=trace", "log_destination": "/tmp/mirrord.log"},
  "target": {
    "path": "deployment/publisher/container/test",
    "namespace": "default"
  },
  "agent": {
    "namespace": "default",
    "log_level": "mirrord=trace",
    "ephemeral": false
  },
  "feature": {
    "network": {
      "incoming": { "mode": "steal", "ignore_localhost": false },
      "outgoing": { "tcp": true, "udp": true, "ignore_localhost": false }
    },
    "fs": "read"
  }
}
```

app
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: test
        image: debian:bookworm
        command:
          - "tail"
          - "-f"
          - "/dev/null"
```

helm:
```yaml
repositories:
  - name: dapr
    url: https://dapr.github.io/helm-charts/

releases:
  - name: dapr
    namespace: dapr-system
    chart: dapr/dapr
    values:
      - global:
          mtls:
            enabled: false
```

mirrord command

`mirrord exec -f .mirrord/mirrord.json /bin/bash`
