### ISSUE TITLE
istio mTLS causes issue

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2851]
Mirantis Kubernetes Engine k8s 1.24
istio mesh with istio-cni

> Health checks are received well and plain text by mirrord, but it also receives some TLS traffic that looks destined to the mTLS/istio (i.e before TLS termination)

**Comment by aviramha** [comment]
reproduced using this istio installation config:
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  components:
    cni:
      namespace: istio-system
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
    egressGateways:
      - name: istio-egressgateway
        enabled: false
```
and following https://istio.io/latest/docs/setup/getting-started/
