### ISSUE TITLE
traffic stealing/mirroring/http filtering is flakey

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#2942]
Local: nixOS + nc (tried also python script to see if it's different and also users' app) Remote: kops cluster running on AWS (not EKS) with calico CNI (vxlan) + Istio mesh It seems that the agent steals/mirrors the connection start but not the data itself for some reason.

Calico configuration from kops:

```
 calico:
      encapsulationMode: vxlan
      mtu: 8951
      typhaReplicas: 3
```

K8s version: v1.27.9
