### ISSUE TITLE
ephemeral targets wrong file system / pid

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#3076]
### Bug Description

while debugging an issue with a customer, we noticed that `/proc/1/cmdline` was `/pause` binary, and the actual PID of the desired container was quite high (43~).
We probably should find a way to get the pid of the desired container and use that instead of using the static `1` pid

### Steps to Reproduce

I don't have clear instructions, but they had crowdstrike init container + sidecar, perhaps the culprit is init containers + sidecars?

### Backtrace

```shell

```

### mirrord layer logs

```shell

```

### mirrord intproxy logs

```shell

```

### mirrord agent logs

```shell

```

### mirrord config

```json

```

### Your operating system and version

n/A

### Local process

N/A

**Comment by meowjesty** [comment]
- `reproduce.yaml` so you can just `kubectl apply -f reproduce.yaml`;

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-serv-deployment
  labels:
    app: py-serv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-serv
  template:
    metadata:
      labels:
        app: py-serv
    spec:
      # Without this, the issue doesn't reproduce.
      shareProcessNamespace: true
      initContainers:
      - name: debian
        image: debian
        command: ['sh', '-c', 'echo "Hello, World!"']
      containers:
        - name: nginx1
          image: nginx
        - name: py-serv
          image: ghcr.io/metalbear-co/mirrord-pytest:latest
          ports:
            - containerPort: 9999
          env:
            - name: MIRRORD_FAKE_VAR_FIRST
              value: mirrord.is.running
            - name: MIRRORD_FAKE_VAR_SECOND
              value: "7777"
            - name: PORT
              value: "9999"
        - name: nginx2
          image: debian
          command: ['sleep', '300000']

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: py-serv
  name: py-serv
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000
  selector:
    app: py-serv
  sessionAffinity: None
  type: NodePort
```
