### ISSUE TITLE
Release 3.137.0 failed

### ISSUE THREAD

**Issue by suzuki-shunsuke** [metalbear-co/mirrord#3210]
https://github.com/metalbear-co/mirrord/releases/tag/3.137.0

No asset was released.

<img width="230" alt="Image" src="https://github.com/user-attachments/assets/bafab6fe-e71c-4002-bf98-2e06ddc53e69" />

The release workflow failed.

https://github.com/metalbear-co/mirrord/actions/runs/14094655149/job/39479373045

```
------
ERROR: failed to solve: failed to push ghcr.io/metalbear-co/mirrord-cli:3.137.0: failed to copy: GET https://productionresultssa7.blob.core.windows.net/actions-cache/366-124925689
--------------------------------------------------------------------------------
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:a212e0ed-501e-0079-4da0-9e5230000000
Time:2025-03-26T22:40:25.8744166Z</Message><AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Wed, 26 Mar 2025 22:26:21 GMT] - Expiry [Wed, 26 Mar 2025 22:36:26 GMT] - Current [Wed, 26 Mar 2025 22:40:25 GMT]</AuthenticationErrorDetail></Error>
--------------------------------------------------------------------------------
```

**Comment by suzuki-shunsuke** [comment]
```
Run docker/build-push-action@v6
  with:
    cache-from: type=gha
    cache-to: type=gha,mode=max
    context: .
    file: mirrord/cli/Dockerfile
    platforms: linux/amd64,linux/arm64
    push: true
    tags: ghcr.io/metalbear-co/mirrord-cli:[3](https://github.com/metalbear-co/mirrord/actions/runs/14094655149/job/39479373045#step:8:3).137.0
  
    load: false
    no-cache: false
    pull: false
    github-token: ***
```

https://github.com/metalbear-co/mirrord/blob/34239ce11a90f9494c1e77fddf3ac3610344d592/.github/workflows/release.yaml#L215-L226

https://github.com/metalbear-co/mirrord/blob/34239ce11a90f9494c1e77fddf3ac3610344d592/.github/workflows/release.yaml#L191-L196
