### ISSUE TITLE
OOMKilled error for the mirrord agent

### ISSUE THREAD

**Issue by elebeaup** [metalbear-co/mirrord#3255]
### Bug Description

It seems there is an issue in the lastest version (3.138.0). If I specify a filter on an HTTP header, the agent is killed due to an out of memory.

### Steps to Reproduce

1. Create a deployment with probes

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: app
        image: mendhak/http-https-echo:35
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

2. Run the program with the mirrord configuration in the description
`mirrord exec -f ./mirrord.json -- python -m http.server 8080`

### Backtrace

```shell

```

### mirrord layer logs

```shell

```

### mirrord intproxy logs

```shell

```

### mirrord agent logs

```shell

```

### mirrord config

```json
{
  "feature": {
    "network": {
      "incoming": {
        "mode": "steal",
        "http_filter": {
          "ports": [
            8080
          ],
          "header_filter": "^User-Agent: (?!kube-probe)"
        }
      },
      "outgoing": false
    },
    "fs": false,
    "env": false
  },
  "target": {
    "path": "deployment/test/container/app",
    "namespace": "meg"
  }
}
```

### mirrord CLI version

3.138.0

### Your operating system and version

Linux Ubuntu 24.04.1 LTS x86_64

### Local process

python

### Additional Info

No OoM in Mirrord 3.137.0
