### ISSUE TITLE
Istio mesh leads to pod notready

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#485]
### Bug Description

When running mirrord in a cluster with Istio mesh with auto injecting enabled the pod spawned by mirrord is injected with a sidecar that renders mirrord useless. The solution would probably be adding the no injection annotation
```yaml
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"

```

### Steps to Reproduce

run mirrord in a istio with auto injection enabled

### Your operating system and version

irrelevant

### Local process

irrelevant
