### ISSUE TITLE
Redefine Target in config file

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#587]
Currently target in config file target is represented as
```toml
target = "type/target/contaner/ect"
target_namespace = "namespace"
```
A better representation for `target` and `target_namespace` in the config file would be a nested one
```toml
target = "type/target/contaner/ect" # "default" as namespace
# OR
target = { path = "type/target/contaner/ect", namespace = "my-namespace"  }
# OR
[target]
path = "type/target/contaner/ect"
namespace = "my-namespace"
```
