### ISSUE TITLE
Move Target enum to Mirrord Config

### ISSUE THREAD

**Issue by DmitryDodzin** [metalbear-co/mirrord#667]
Currently we parse `Target` enum from the value saved in `LayerConfig` as a `String`, parsing the `Target` as part of mirrord-config will allow us to improve user experience by allowing config like
```toml
[target]
pod = "foo"
container = "bar"
```
or
```toml
[target]
path = { pod = "foo", container = "bar" }
namespace = "namespace"
```
and still retain the shorter version of
```toml
target = "pod/foo/container/bar"
```
