### ISSUE TITLE
Mounted filesystem/configmap/secret not working

### ISSUE THREAD

**Issue by niconatalie** [metalbear-co/mirrord#789]
### Bug Description

Hi, I have golang application running in k8s cluster and it mounted volumes from secrets and configmap, but when I run the application, it fails because it cannot find the path to the directory.

### Steps to Reproduce

1. Have running application on k8s with mounted volumes from configmap and secrets.
   ```
   containers:
    volumeMounts:
      - name: token
        mountPath: /etc/github
        readOnly: true
      - name: config
        mountPath: /etc/config
        readOnly: true
   volumes:
     - name: token
       secret:
         secretName: token
     - name: config
       configMap:
         name: config
   ```
2. Run `mirrord exec ./main --target pod/<pod-name>`

### Your operating system and version

Linux Ubuntu 18.04.6 LTS

### Local process

./main: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=94de9fb4751f32af5cc6a567323cdf5c32b32478, with debug_info, not stripped

**Comment by aviramha** [comment]
hey @niconatalie 
Sorry about the issue. This probably happens because `/etc/*` is excluded by default.
We're working on making the exclusions more fine-grained, meanwhile you can try to run mirrord with env var
`MIRRORD_FILE_FILTER_INCLUDE=/etc/config` and that should bypass the exclusion. Note that when using include it will include only those files, so if you need more files you can build a regex with "or" (`|`)

**Comment by niconatalie** [comment]
@aviramha I see, thank you for information and the tips. I will try it

**Comment by aviramha** [comment]
Hey,
just a heads up, we released a new version that supports better control over files.
For your use case you can use
```toml
accept_invalid_certificates = false

[feature]
env = true

[feature.network]
incoming = "mirror"
outgoing = true

[feature.fs]
mode = "read"
read_only = [ "/etc/github", "/etc/config" ]
```
This will override our regex and make it read those `etc` files from remote even though we exclude it by default (we exclude `/etc/`)
