### ISSUE TITLE
Reading mounted directory fails

### ISSUE THREAD

**Issue by f-blass** [metalbear-co/mirrord#902]
### Bug Description

When trying to read a mounted directory it fails with `fdopendir /tmp/foo: not a directory`

### Steps to Reproduce

1. Create a pod with a volume mount (e.g. /tmp/foo/bar)
2. Try to read the directory `foo`
3. See the error

### Relevant Logs
[Rust Trace Logs](https://github.com/metalbear-co/mirrord/files/10345141/read-dir-trace.log)
Logs are stripped to the dir reading parts.

### Your operating system and version

MacBook Pro M1 Max; macOS 13.1 (22C65)

### Local process

/private/var/folders/lb/y5b0sgds5nv7z_vr4y9z68kc0000gn/T/GoLand/___go_build_playground_dir: Mach-O 64-bit executable arm64

### Local process version

go version go1.19.4 darwin/arm64

### Additional Info

I used the GoLand plugin.

<details>
<summary>Minimal program example</summary>

```go
package main

import (
	"fmt"
	"os"

	"C"
)

func main() {
	fmt.Println("==== DIR ====")
	stat, err := os.Stat("/tmp/foo")
	if err != nil {
		fmt.Print(err)
		return
	}

	fmt.Printf("Name: %s\n", stat.Name())
	fmt.Printf("Mode String: %s\n", stat.Mode().String())
	fmt.Printf("Mode IsDir: %v\n", stat.Mode().IsDir())
	fmt.Printf("Size: %v\n", stat.Size())

	dir, err := os.ReadDir("/tmp/foo")
	if err != nil {
		fmt.Printf("Reading dir error: %s\n", err)
	} else {
		fmt.Printf("DirEntries: %v\n", dir)
	}

	fmt.Println("==== FILE ====")
	stat, err = os.Stat("/tmp/foo/bar")
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("Name: %s\n", stat.Name())
	fmt.Printf("Mode String: %s\n", stat.Mode().String())
	fmt.Printf("Mode IsDir: %v\n", stat.Mode().IsDir())
	fmt.Printf("Size: %v\n", stat.Size())

	file, err := os.ReadFile("/tmp/foo/bar")
	if err != nil {
		fmt.Printf("Reading file error: %s\n", err)
	} else {
		fmt.Printf("File Content: %s\n", file)
	}
}
```

</details>

<details>
<summary>Minimal program output</summary>

```
==== DIR ====
Name: foo
Mode String: drwxrwxrwx
Mode IsDir: true
Size: 4096
Reading dir error: fdopendir /tmp/foo: not a directory
==== FILE ====
Name: bar
Mode String: -rw-r--r--
Mode IsDir: false
Size: 6
File Content: foobar
```

</details>

**Comment by aviramha** [comment]
Thanks for the report! We don't support this at the moment, see #120.
If this is significant to you, we will prioritize adding support.

**Comment by f-blass** [comment]
Thanks for the quick feedback! It is kinda crucial for our use case as we are reading secrets dynamically from a folder. 


We typically do something like the following: 

A volume is created out of the secret
```
volumes:
  - name: objecstore-1-creds
    secret:
      secretName: objectstore-1
  - name: objecstore-2-creds
    secret:
      secretName: objectstore-2
```

and mounted to the container
```
volumeMounts:
  - name: objectstore-1-creds
    mountPath: "/etc/secrets/objectstore/objectstore-1"
    readOnly: true
  - name: objectstore-2-creds
    mountPath: "/etc/secrets/objectstore/objectstore-2"
    readOnly: true
```

The objectstore folder is read and all files below are parsed.
This might be some special scenario, not sure if other users are also facing similar challenges. So not sure about the general importance to support this in mirrord.
